# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stream_service_pb2 as stream__service__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stream_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RTSPStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartStream = channel.unary_unary(
                '/streamingservice.RTSPStreamService/StartStream',
                request_serializer=stream__service__pb2.StartRequest.SerializeToString,
                response_deserializer=stream__service__pb2.StartResponse.FromString,
                _registered_method=True)
        self.StopStream = channel.unary_unary(
                '/streamingservice.RTSPStreamService/StopStream',
                request_serializer=stream__service__pb2.StopRequest.SerializeToString,
                response_deserializer=stream__service__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetLatestFrame = channel.unary_unary(
                '/streamingservice.RTSPStreamService/GetLatestFrame',
                request_serializer=stream__service__pb2.FrameRequest.SerializeToString,
                response_deserializer=stream__service__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/streamingservice.RTSPStreamService/StreamFrames',
                request_serializer=stream__service__pb2.StreamRequest.SerializeToString,
                response_deserializer=stream__service__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.CheckStream = channel.unary_unary(
                '/streamingservice.RTSPStreamService/CheckStream',
                request_serializer=stream__service__pb2.CheckRequest.SerializeToString,
                response_deserializer=stream__service__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.ListStreams = channel.unary_unary(
                '/streamingservice.RTSPStreamService/ListStreams',
                request_serializer=stream__service__pb2.ListStreamsRequest.SerializeToString,
                response_deserializer=stream__service__pb2.ListStreamsResponse.FromString,
                _registered_method=True)
        self.UpdateStream = channel.unary_unary(
                '/streamingservice.RTSPStreamService/UpdateStream',
                request_serializer=stream__service__pb2.UpdateStreamRequest.SerializeToString,
                response_deserializer=stream__service__pb2.UpdateStreamResponse.FromString,
                _registered_method=True)


class RTSPStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """流式传输
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStreams(self, request, context):
        """查询所有流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStream(self, request, context):
        """更新流信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RTSPStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=stream__service__pb2.StartRequest.FromString,
                    response_serializer=stream__service__pb2.StartResponse.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=stream__service__pb2.StopRequest.FromString,
                    response_serializer=stream__service__pb2.StopResponse.SerializeToString,
            ),
            'GetLatestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestFrame,
                    request_deserializer=stream__service__pb2.FrameRequest.FromString,
                    response_serializer=stream__service__pb2.FrameResponse.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=stream__service__pb2.StreamRequest.FromString,
                    response_serializer=stream__service__pb2.FrameResponse.SerializeToString,
            ),
            'CheckStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStream,
                    request_deserializer=stream__service__pb2.CheckRequest.FromString,
                    response_serializer=stream__service__pb2.CheckResponse.SerializeToString,
            ),
            'ListStreams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStreams,
                    request_deserializer=stream__service__pb2.ListStreamsRequest.FromString,
                    response_serializer=stream__service__pb2.ListStreamsResponse.SerializeToString,
            ),
            'UpdateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStream,
                    request_deserializer=stream__service__pb2.UpdateStreamRequest.FromString,
                    response_serializer=stream__service__pb2.UpdateStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamingservice.RTSPStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamingservice.RTSPStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RTSPStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamingservice.RTSPStreamService/StartStream',
            stream__service__pb2.StartRequest.SerializeToString,
            stream__service__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamingservice.RTSPStreamService/StopStream',
            stream__service__pb2.StopRequest.SerializeToString,
            stream__service__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamingservice.RTSPStreamService/GetLatestFrame',
            stream__service__pb2.FrameRequest.SerializeToString,
            stream__service__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/streamingservice.RTSPStreamService/StreamFrames',
            stream__service__pb2.StreamRequest.SerializeToString,
            stream__service__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamingservice.RTSPStreamService/CheckStream',
            stream__service__pb2.CheckRequest.SerializeToString,
            stream__service__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStreams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamingservice.RTSPStreamService/ListStreams',
            stream__service__pb2.ListStreamsRequest.SerializeToString,
            stream__service__pb2.ListStreamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamingservice.RTSPStreamService/UpdateStream',
            stream__service__pb2.UpdateStreamRequest.SerializeToString,
            stream__service__pb2.UpdateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
