services:
  grpc_rtsp:
    build:
      context: .
      dockerfile: Dockerfile
    image: grpc_rtsp_server
    container_name: grpc_rtsp_server
    runtime: nvidia
    ipc: host
    shm_size: 2g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "50051:50051"
    stdin_open: true
    tty: true
    restart: unless-stopped